### ISSUE TITLE
Question about FileManager: Is it per folder or per file?

### ISSUE THREAD

**Issue by liach** [FlibioStudio/Utils#1]
Currently, each instance of file manager is for a folder. I suggest to change it to be based on each file, which could prevent the manager from creating the file for multiple times.

**Comment by Flibio** [comment]
Each plugin should have one instance of the FileManager. See JobsLite for an example.

**Comment by liach** [comment]
I suggest to have one instance for each config file. `FileManager` is not really a singleton.

**Comment by Flibio** [comment]
I'll look into changing it.
